### ISSUE TITLE
Pouvoir mettre plusieurs thématiques et plusieurs étapes

### ISSUE THREAD

**Issue by SalomeDeschenes** [PerrineRut/urbanvitaliz#36]
urbanvitaliz/TMP_resources/Appui_EPORA.md

**Comment by DavidBruant** [comment]
Normallement, c'est corrigé

[voilà à quoi ça ressemble en markdown de mettre 2 thématiques](https://github.com/betagouv/urbanvitaliz/commit/0bf5303f093217c4ffbf355acc295cbdb10f662f#diff-48f6e95883f2789967712eb5054192e0eec47a0c8fc786dcc12d83d520bd089d) : 

```yml
thematique : 
    - "Portage foncier"
    - "Conseil & ingénerie"
```
